backend:
  name: github
  repo: osman289/kurankursu-web
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "slider"
    label: "Ana Sayfa Kayan Fotograflar"
    files:
      - name: "slider"
        label: "Kayan Fotograflar"
        file: "data/slider.json"
        fields:
          - name: slides
            label: Fotograflar
            widget: list
            fields:
              - {name: image, label: Masaüstü Fotoğrafı, widget: image}
              - {name: mobileImage, label: Mobil Fotoğrafı, widget: image, required: false}
              - {name: title, label: Baslik, widget: string, required: false}
              - {name: description, label: Aciklama, widget: string, required: false}

  - name: "gallery"
    label: "Medya ve Galeri"
    files:
      - name: "gallery"
        label: "Galeri Fotograflari"
        file: "data/gallery.json"
        fields:
          - name: images
            label: Fotograflar
            widget: list
            fields:
              - {name: image, label: Fotograf, widget: image}
              - {name: category, label: Kategori, widget: select, options: ["Siniflarimiz", "Etkinlikler", "Mezuniyet Toreni", "Kursumuz"]}
              - {name: caption, label: Baslik, widget: string, required: false}

  - name: "staff"
    label: "Kadromuz"
    files:
      - name: "staff"
        label: "Personel Listesi"
        file: "data/staff.json"
        fields:
          - name: members
            label: Personel
            widget: list
            fields:
              - {name: name, label: Isim, widget: string}
              - {name: role, label: Gorev, widget: string}
              - {name: type, label: Tur (Kategori), widget: select, options: ["Yonetim", "Egitimci", "Belletmen"]}
              - {name: image, label: Profil Fotografi, widget: image, required: false}
